blank_issues_enabled: false
contact_links:
  - name: Improve Country - discussions
    url: https://github.com/improvecountry/ideas/discussions
    about: Please ask and answer questions here.
  - name: Improve Country - Introduction (en)
    url: https://github.com/improvecountry/ideas/wiki/introduction#introduction
    about: Read Introduction to Improve Country.
  - name: Improve Country - Wstęp (pl)
    url: https://github.com/improvecountry/ideas/wiki/Introduction#wstęp
    about: Przeczytaj Wstęp do Improve Country.
  - name: Improve Country - regulations (en)
    url: https://github.com/improvecountry/ideas/wiki/regulations
    about: Read Regulations of Improve Country in English.
  - name: Improve Country - Regulamin (pl)
    url: https://github.com/improvecountry/ideas/wiki/regulamin
    about: Przeczytaj Regulamin Improve Country w języku polskim.