name: Idea for Poland 叼 (pl)
description: Je偶eli nie znasz jzyka angielskiego skorzystaj z tego formularza, aby przesa sw贸j pomys na usprawnienie Polski w jzyku  polskim.
#title: "[idea]: "
labels: [Poland, Polish]
body:
  - type: markdown
    attributes:
      value: |
        Dzikuj za czas powicony na wypenienie tego formularza!

        > Zanim zgosisz sw贸j nowy pomys upewnij si czy kto ju偶 tego wczeniej nie zrobi. List wszystkich pomys贸w znajdziesz [tutaj](https://github.com/improvecountry/ideas/issues).

  - type: textarea
    id: problem-description
    attributes:
      label: Opis problemu
      description: Opisz czego dotyczy problem.
      placeholder: Co nie dziaa tak jak powinno? Rozwizanie jakiego problemu w og贸le nie istnieje? Opisz to tutaj.
    validations:
      required: true
  - type: textarea
    id: solution-proposal
    attributes:
      label: Propozycja rozwizania
      description: Opisz sw贸j pomys na rozwizanie zgoszonego problemu. Je偶eli posiadasz jakie rysunki lub mockupy mo偶esz je zaczy tutaj.
      placeholder: Przykadowym rozwizaniem dla opisanego problemu mo偶e by...
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternatywne rozwizania
      description: Podaj przykady alternatywnych lub tymczasowych rozwiza, je偶eli istniej.
      placeholder: Oczekujc na finalne rozwizanie dobr alternatyw lub tymczasowym rozwizaniem dla opisanego problemu mo偶e by...
    validations:
      required: false

  - type: textarea
    id: example-solutions
    attributes:
      label: Przykadowe rozwizania
      description: Je偶eli wiesz o rozwizaniach, kt贸re ju偶 teraz istniej i speniaj swoj rol w innych miastach lub krajach wymie je tutaj.
      placeholder: |
        1. 
        2. 
        3. 
        ...
    validations:
      required: false

  - type: dropdown
    id: consent
    attributes:
      label: Zgoda
      description: Czy chcesz, aby na Licie Pomysodawc贸w umieszczono nazw Twojego konta w serwisie GitHub oraz linku do Twojego profilu w serwisie GitHub, Twoje imi i nazwisko przez Realizatora? Zaznacz odpowiednie opcje.
      multiple: true
      options:
        - Wyra偶am zgod na umieszczenie nazwy oraz linku do mojego profilu w serwisie GitHub na Licie Pomysodawc贸w.
        - Wyra偶am zgod na umieszczenie mojego imienia i nazwiska na Licie Pomysodawc贸w.
        - Wyra偶am zgod na umieszczenie nazwy oraz linku do mojego profilu w serwisie GitHub oraz mojego imienia i nazwiska na Licie Pomysodawc贸w.

  - type: checkboxes
    id: terms
    attributes:
      label: Regulamin
      description: Wysyajc sw贸j pomys zgadzasz si na przestrzeganie [Regulaminu Improve Country (jzyk polski)](https://github.com/improvecountry/ideas/wiki/regulamin), [Regulations of Improve Country (English)](https://github.com/improvecountry/ideas/wiki/regulations)
      options:
        - label: Zgadzam si na przestrzeganie Regulaminu Improve Country.
          required: true

  - type: markdown
    attributes:
      value: "### Etykiety (en. Labels)"
  - type: markdown
    attributes:
      value: |
        Kliknij w 锔 po prawej stronie sekcji **Labels** (pl. Etykiety) umieszczonej poni偶ej lub po prawej stronie tego formularza i przypisz jedn lub wicej etykiet do Twojego pomysu. W przypadku gdy nie znajdziesz etykiety odpowiedniej dla Twojego pomysu wybierz etykiet `NO CATEGORY`.
        
        > Etykiety `Poland` oraz `Polish` s domylnie przypisanymi etykietami. Pozostaw je przypisane.
